### ISSUE TITLE
后续会加上登陆功能吗

### ISSUE THREAD

**Issue by quert999** [blackbbc/Tucao#10]
而且我看官网的app下载也是百度云，难道你这个就是官方app吗

**Comment by blackbbc** [comment]
1. 会加上登陆功能，并且在考虑做出类似 https://dash.readme.io/login 的登录窗和 https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B14F_FSUCc01WjI3ZmdRYUV5ZDA/Radial_04_RadialArc_v5-remapped.webm 的转场效果，但是要等6月毕业答辩完再做。
2. 是的，官网的第一个下载链接就是这个APP。不能算是官方的吧，这个只是我的个人作品，然后小神（C站站长）觉得还不错就帮我推广上去了。

**Comment by quert999** [comment]
大神请收下我的膝盖。。。
太强了，完全吊打小公司两三年的程序员。。

**Comment by quert999** [comment]
dalao容我厚颜无耻的问一下，那个转场效果在哪里看的。。。我在谷歌安卓design下面找了好久也没找到类似的效果展示。。。

**Comment by blackbbc** [comment]
https://material.io/guidelines/motion/transforming-material.html#transforming-material-radial-transformation
