### ISSUE TITLE
项目clone下来少GSYVideoPlayer @ aa43d7c文件

### ISSUE THREAD

**Issue by HRobbie** [blackbbc/Tucao#12]
1.项目clone下来少GSYVideoPlayer @ aa43d7c文件
2.集成了GSYVideoPlayer之后运行出现问题如下图
![image](https://cloud.githubusercontent.com/assets/17965602/26284970/f1caafbc-3e78-11e7-893d-971def6fb8ce.png)

**Comment by blackbbc** [comment]
#3
