### ISSUE TITLE
rxlifecycle依赖问题

### ISSUE THREAD

**Issue by quert999** [blackbbc/Tucao#15]
我把依赖改成最新版的2.1.0之后无法依赖成功。
提示failed to resolve: android.arch.lifecycle:runtime:1.0.0-alpha1
但是使用你这个项目里面的2.0.1是可以依赖成功的。。。
是因为需要翻墙吗，但是我开蓝灯竟然也不行。。
这个问题我不会用英语描述，所以就没跑到rxlifecycle上面提issue了。。。
dalao看看你会不会也出这个问题

**Comment by blackbbc** [comment]
这个月在忙毕业，过段时间再看

**Comment by blackbbc** [comment]
Google家的arch库需要翻墙
