### ISSUE TITLE
有遇到这个问题吗？编译报错org.jetbrains.kotlin.kapt3.diagnostic.KaptError: Error while annotation processing

### ISSUE THREAD

**Issue by junquanvip** [blackbbc/Tucao#16]
:D:\wordplace\other\tucao\Tucao\app\build\tmp\kapt3\stubs\debug\me\sweetll\tucao\di\component\ApiComponent.java:5: 错误: 不兼容的类型: NonExistentClass无法转换为Annotation
e: 

e: @error.NonExistentClass()
e:       ^
e: java.lang.IllegalStateException: failed to analyze: org.jetbrains.kotlin.kapt3.diagnostic.KaptError: Error while annotation processing
	at org.jetbrains.kotlin.analyzer.AnalysisResult.throwIfError(AnalysisResult.kt:57)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules(KotlinToJVMBytecodeCompiler.kt:144)

**Comment by blackbbc** [comment]
Android Studio版本是3.0 canary 7吗

**Comment by junquanvip** [comment]
不是，刚换了3.0 canary 7居然就好了
