### ISSUE TITLE
封面图的缩放（scaleType）有问题

### ISSUE THREAD

**Issue by DanteAndroid** [blackbbc/Tucao#17]
![image](https://user-images.githubusercontent.com/10005563/29159986-1aae5a24-7de3-11e7-8aab-090c39763252.png)
类似于这种图片被拉伸的情况。不知道是图片本身问题还是缩放设置有问题

**Comment by blackbbc** [comment]
我设的是 fitXY 所以被拉伸了
有什么建议吗

**Comment by DanteAndroid** [comment]
fitXY一般都不用的。。。建议`centerCrop`吧，比较稳

**Comment by blackbbc** [comment]
妥
