### ISSUE TITLE
问一下1.1.3下载视频需要什么系统模块。

### ISSUE THREAD

**Issue by fuchanghao** [blackbbc/Tucao#18]
我下载从1.1.2开始就出现一点下载APP就停止响应问题，权限什么的都给了。

系统是安卓6.0.1。

不清楚是什么导致的，是不是某些系统模块缺失的问题。

其它APP比如A站和B站的都下载视频正常。

**Comment by blackbbc** [comment]
好象是打包的时候出现了问题，我检查一下

**Comment by fuchanghao** [comment]
感谢修正，1.1.4已经正常。
