### ISSUE TITLE
能否增加支持tv遥控操作

### ISSUE THREAD

**Issue by travison** [blackbbc/Tucao#2]
感谢作者,使用下来很舒服。不知能否加入支持tv遥控操作, 这样就能在大屏幕看隔壁没拿下的番了。

**Comment by quert999** [comment]
作者dalao，如果我要学习kotlin，怎么系统的学习啊。
前段时间看了一点基础语法，老感觉疏漏了很多东西。。。

**Comment by blackbbc** [comment]
先把kotlin-koans的所有习题做完：
https://try.kotlinlang.org/
https://github.com/Kotlin/kotlin-koans
然后看一下Jake Wharton大神对于Kotlin在Android上的应用的演讲：
https://www.youtube.com/watch?v=A2LukgT2mKc
https://www.youtube.com/watch?v=0sPzDwS55wM
然后就可以开始用Kotlin撸一个项目了，推荐gank.io的客户端
PS：anko可以不学，我个人觉得没有xml来得快以及用anko撸动画比较蛋疼

**Comment by blackbbc** [comment]
https://tieba.baidu.com/p/5291825929

**Comment by travison** [comment]
厉害了 多谢提醒
