### ISSUE TITLE
gsyVideoPlayer报错

### ISSUE THREAD

**Issue by ycyranqingjjs** [blackbbc/Tucao#20]
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :gsyVideoPlayer. Open File Show Details

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :gsyVideoPlayer. Open File Show Details

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :gsyVideoPlayer. Open File Show Details

**Comment by blackbbc** [comment]
git clone --recursive -j8 https://github.com/blackbbc/Tucao.git

**Comment by Everglowzz** [comment]
> --recursive -j8

怎么操作~
