### ISSUE TITLE
MalformedByteSequenceException: 3 字节的 UTF-8 序列的字节 3 无效。

### ISSUE THREAD

**Issue by syusikoku** [blackbbc/Tucao#22]
e: java.lang.IllegalStateException: failed to analyze: android.databinding.tool.util.LoggedErrorException: failure, see logs for details.
Exception while handling step android.databinding.annotationprocessor.ProcessExpressions@214213fe javax.xml.bind.UnmarshalException
 - with linked exception:
[com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: 3 字节的 UTF-8 序列的字节 3 无效。]

**Comment by blackbbc** [comment]
https://github.com/blackbbc/Tucao/issues/4
https://github.com/blackbbc/Tucao/issues/7
