### ISSUE TITLE
为什么提示找不到.so文件呢？

### ISSUE THREAD

**Issue by youkongyi** [blackbbc/Tucao#26]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: me.sweetll.tucao, PID: 7742
java.lang.UnsatisfiedLinkError: 
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.sweetll.tucao-JRf82aI4PhqqEs_GqF24Ew==/base.apk", 
zip file "/data/app/me.sweetll.tucao-JRf82aI4PhqqEs_GqF24Ew==/split_lib_dependencies_apk.apk", 
zip file "/data/app/me.sweetll.tucao-JRf82aI4PhqqEs_GqF24Ew==/split_lib_slice_0_apk.apk", 
zip file "/data/app/me.sweetll.tucao-JRf82aI4PhqqEs_GqF24Ew==/split_lib_slice_1_apk.apk", 
zip file "/data/app/me.sweetll.tucao-JRf82aI4PhqqEs_GqF24Ew==/split_lib_slice_2_apk.apk", 
zip file "/data/app/me.sweetll.tucao-JRf82aI4PhqqEs_GqF24Ew==/split_lib_slice_3_apk.apk", 
zip file "/data/app/me.sweetll.tucao-JRf82aI4PhqqEs_GqF24Ew==/split_lib_slice_4_apk.apk", 
zip file "/data/app/me.sweetll.tucao-JRf82aI4PhqqEs_GqF24Ew==/split_lib_slice_5_apk.apk", 
zip file "/data/app/me.sweetll.tucao-JRf82aI4PhqqEs_GqF24Ew==/split_lib_slice_6_apk.apk", 
zip file "/data/app/me.sweetll.tucao-JRf82aI4PhqqEs_GqF24Ew==/split_lib_slice_7_apk.apk", 
zip file "/data/app/me.sweetll.tucao-JRf82aI4PhqqEs_GqF24Ew==/split_lib_slice_8_apk.apk", 
zip file "/data/app/me.sweetll.tucao-JRf82aI4PhqqEs_GqF24Ew==/split_lib_slice_9_apk.apk"],
nativeLibraryDirectories=[/data/app/me.sweetll.tucao-JRf82aI4PhqqEs_GqF24Ew==/lib/x86, /system/lib, /vendor/lib]]] 
couldn't find "libijkffmpeg.so"

F:\androidProject\Tucao\ijkplayer-armv7a\src\main\libs\armeabi-v7a\libijkffmpeg.so 
在文件中是有so文件的。

**Comment by blackbbc** [comment]
你是在模拟器中打开的吗，要看架构
大多数手机都是arm架构，所以armeabi的so包就够了
很多模拟器是x86的，所以需要x86的so包，但是我没有加
你可以试试把`app/build.gradle`中的
```
ndk {
    abiFilters 'armeabi-v7a'/*, 'x86'*/
 }
```
注释删掉

**Comment by youkongyi** [comment]
我添加了ndk 是这样的,会有冲突么？
ndk {
            abiFilters 'armeabi', 'armeabi','x86', 'armeabi-v7a', 'x86_64', 'arm64-v8a'
        }

**Comment by blackbbc** [comment]
只需要armeabi-v7a和x86就够了，向下兼容的，加多了会导致apk包巨大的。
