### ISSUE TITLE
请教一下 GSYVideoPlayer 这个类库是如何依赖的

### ISSUE THREAD

**Issue by done134** [blackbbc/Tucao#3]
如题，我把您的项目克隆到我的本地，在android studio 中出现这个问题
Invalid VCS root mapping
         The directory D:\T***\GSYVideoPlayer is registered as a Git root, but no Git repositories were found there.

**Comment by blackbbc** [comment]
是以`Sub Module`形式依赖的
请使用以下命令Clone仓库

```
git clone --recursive -j8 https://github.com/blackbbc/Tucao.git
```

更多关于`git sub module`的相关信息请参考：
https://git-scm.com/book/zh/v1/Git-工具-子模块

**Comment by syusikoku** [comment]
$ git clone --recursive -j8 https://github.com/blackbbc/Tucao.git
Cloning into 'Tucao'...
remote: Counting objects: 10047, done.
remote: Total 10047 (delta 0), reused 0 (delta 0), pack-reused 10047
Receiving objects: 100% (10047/10047), 33.04 MiB | 909.00 KiB/s, done.
Resolving deltas: 100% (5265/5265), done.
Checking connectivity... done.
Submodule 'GSYVideoPlayer' (https://github.com/blackbbc/GSYVideoPlayer.git) registered for path 'GSYVideoPlayer'
Cloning into 'E:/项目收集/kotlin/tc/Tucao/GSYVideoPlayer'...
到这里就一直没有进度了
