### ISSUE TITLE
clean no problem, and  so compile  it is .but when I run the app it  report these errors. I can't understand

### ISSUE THREAD

**Issue by hongming1218** [blackbbc/Tucao#6]
Error:java.lang.RuntimeException: Failed to parse data binding compiler options. Params:
Error:java.lang.NumberFormatException: null
Error:Execution failed for task ':app:kaptDebugKotlin'.
> Compilation error. See log for more details

**Comment by blackbbc** [comment]
Please show the complete log.
But I think compile should not be the problem because I use travis ci to auto compile my project.
https://travis-ci.org/blackbbc/Tucao

**Comment by hongming1218** [comment]
my trouble,  gradle  didn't  add   kotlin
