### ISSUE TITLE
AppApplication    #47    我不确定是不是缺东西了？

### ISSUE THREAD

**Issue by hongming1218** [blackbbc/Tucao#9]
需要包import me.sweetll.tucao.di.component.DaggerBaseComponent
在me.sweetll.tucao.di.component文件夹下没有找到对应的DaggerBaseComponent

**Comment by blackbbc** [comment]
Dagger自动生成的类
需要Rebuild后才有

**Comment by hongming1218** [comment]
嗯  好了 编译器问题  修改了下gradle重新build   直接rebuild竟然没管用   thx

**Comment by StephenGiant** [comment]
我搞清楚了 是databinding引起的
